### ISSUE TITLE
ts file compilation issue

### ISSUE THREAD

**Issue by angu2starter** [gilf/angular2-indexeddb#1]
I added the angular2-indexeddb.ts file in my project, so that I can import AngularIndexedDB. However I am getting 15 compilation errors when I added the class in webstorm IDE. The errors are mainly on the  readonly attribute of DbMode class, result variable used in getByIndex and getAll methods. My dependencies are
"dependencies": {
    "angular2": "2.0.0-beta.13",
    "systemjs": "0.19.25",
    "es6-shim": "^0.35.0",
    "ng2-bootstrap": "^1.0.10",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "typescript": "^1.8.9",
	"es6-promise": "^3.0.2",
    "typings":"^0.7.11",
	"autoprefixer": "^6.2.1",
    "cssnano": "^3.4.0",
	"gulp": "^3.9.0",
    "gulp-ext-replace": "^0.2.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-postcss": "^6.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.10.0",
    "gulp-uglify": "^1.5.1",
    "postcss": "^5.0.13",
    "postcss-scss": "^0.1.3",
    "precss": "^1.3.0",    
	"gulp-webserver": "^0.9.1"
  }

I am eager to use it, please help me to resolve these issues.

**Comment by gilf** [comment]
Hi angu2starter,

I've just uploaded a new version that should fix the problems you mentioned. 
Let me know if it helped.

Gil

**Comment by angu2starter** [comment]
Thanks Gil, that took care of lot of errors. Now when I am calling the method "add(storeName: string, value: any, key: any)" to add values to the store I am getting an error "Potentially unhandled rejection [1] TypeError: Cannot read property 'contains' of undefined". After debugging I found that in validateStoreName method of DbWrapper class, this.db.objectStoreNames is always undefined.
 validateStoreName(storeName) {
        return this.db.objectStoreNames.contains(storeName);
    };

Also there is a variable named  storeNames: Array<string>; defined in DBWrapper that never seems to be used.

If possible could you please add a method to just add values to store.. something like add(storeName: string, value: any).

Thanks again and look forward for your response.

**Comment by angu2starter** [comment]
If I comment the following lines from validateBeforeTransaction() method and execute the code 

if (!this.validateStoreName(storeName)) {
     reject(('objectStore does not exists: ' + storeName));
}

then I am getting another error saying: "Potentially unhandled rejection [1] TypeError: this.db.transaction is not a function" which is thrown from the code
let trans: IDBTransaction = this.db.transaction(options.storeName, options.dbMode);

of createTransaction() method

**Comment by gilf** [comment]
Hi angu2starter,

I defined the db type to be IDBDatabase which should fix the errors you see.
I also omitted the member you mentioned (which was related to a previous version and is not used anymore).

Gil

**Comment by angu2starter** [comment]
Thank you Gil, whenever you get a chance could you please push the latest changes.

**Comment by gilf** [comment]
My bad.
Only committed the fix locally and didn't pushed it.
Let me know if you have any other problem.
