### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by FallenRiteMonk** [gilf/angular2-indexeddb#13]
I implemented this service in a small project of mine which was build using angular-cli (beta 24). The problem I encounter is tat I'm not able to build the project using the AOT parameter due to this error:
```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in <PROJECT_PATH>/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in <PROJECT_PATH>/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in <PROJECT_PATH>/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '<PROJECT_PATH>/src'
 @ ./src/main.ts 5:0-74
 @ multi main

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve '<PROJECT_PATH>/src/$$_gendir' in '<PROJECT_PATH>/node_modules/@angular/core/src/linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main
```

This blog helped me in making another library AOT ready:
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.it1dbfyro

**Comment by pictaile** [comment]
I have error for build app. `ng build --prod`. 

I have Angular4. How fixed it?

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not
supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectab
le in F:/Projects/crew/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol
 OpaqueToken in F:/Projects/crew/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_token.d.ts, re
solving symbol OpaqueToken in F:/Projects/crew/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_
token.d.ts
