### ISSUE TITLE
objectStore does not exists 

### ISSUE THREAD

**Issue by ghatul** [gilf/angular2-indexeddb#14]
i want to create more than one object store with same indexses but stuck with error objectStore does not exists .

    this.dbService.createDB('skillcontext', (evt:any)=> {
      console.log('---------------------1--------------------------------');
    });
    this.dbService.createDB('math', (evt:any)=> {
      console.log('---------------------2--------------------------------');
    });

math object store is created all time but stuck on skillcontext object

**Comment by gilf** [comment]
Hi @ghatul,

Please refer to the API and how to use it.
There is no createDB function but rather there is a createStore function which gets as a parameter a database version number (have to be a number) and a callback that will be called when the indexeddb upgradeneeded event is called. If the version number isn't changed between the calls to createStore nothing will happen and the upgradeneeded event wouldn't be fired.
