### ISSUE TITLE
 Error on fetch for angular2-indexeddb.js

### ISSUE THREAD

**Issue by ghatul** [gilf/angular2-indexeddb#15]
I use this seed for starter project. [https://github.com/vyakymenko/angular2-seed-express](url)

but i stuck with configuration of indexdb on production build it get Error on fetch for angular2-indexeddb.js.
i cant understand how to solve this, could u please help me out.....

error:-

[18:45:25] 'build.bundles.app' errored after 2.82 s
[18:45:25] Error on fetch for angular2-indexeddb.js at file:///home/node_modules/angular2-indexeddb.js
        Loading dist/tmp_client/app//db-service/db.service.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        Error: ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
    at Error (native)
[18:45:25] 'build.prod' errored after 33 s
[18:45:25] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for angular2-indexeddb.js at file:///home/node_modules/angular2-indexeddb.js
        Loading dist/tmp_client/app/qeasily/framework/db-service/db.service.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
Stack:
Error on fetch for angular2-indexeddb.js at file:///home/chetan/node_modules/angular2-indexeddb.js
        Loading dist/tmp_client/app/framework/db-service/db.service.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        Error: ENOENT: no such file or directory, open '/home/chetan/node_modules/angular2-indexeddb.js'
    at Error (native)

**Comment by gilf** [comment]
Hi @ghatul,

From the error I see in the stack trace you provided your bundler (which is part of your build) tries to get the angular2-indexeddb.js from the node_modules folder. When you install the library it should be under node_modules/angular2-indexeddb and this is why the bundler doesn't find it. Please check the bundler code to see why it tries to fetch the file not from its location.
