### ISSUE TITLE
how use component?

### ISSUE THREAD

**Issue by pictaile** [gilf/angular2-indexeddb#2]
I right understood? I will install indexeddb and install angular2-indexeddb? If right, How install indexeddb?

**Comment by gilf** [comment]
Currently, you download the angular2-indexeddb.min.js file. You put it in your app's third party libraries folder and then add the script to your app (using a script tag or loading it with a script loader such as SystemJS). After you do that you can import the the AngularIndexedDB class and start working with it.
Another option is to fetch the entire library into your node_modules and then use the angular2-indexeddb TypeScript version.
