### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by migueluvieu** [gilf/angular2-indexeddb#20]
Hi. I have a error when import js into my index.html
Uncaught ReferenceError: exports is not defined
    at angular2-indexeddb.ts:11
My versions:
"@angular/...": "^2.4.0"
"typescript": "~2.0.0" 

Can you help me please?

Thanks!

**Comment by ilanov** [comment]
Hi,

Is this one solved???

Thanks!

**Comment by migueluvieu2** [comment]
No :( ... I decided to use AngularFireOffline in my pwa application ... Have you tried localforage? https://github.com/ocombe/angular-localForage

**Comment by ilanov** [comment]
Eventually it is not needed to import the js file in index.html in case that you are using typescript.
Just skip this step. It should work.

**Comment by gilf** [comment]
Hi,

Sorry for the late response. 
As ilanov wrote, you don't need to import the generated js file and you should use import with the TS code. Another option is to use a bundler such as Webpack or Browserify to bundle the code so you won't need to import the js file.

**Comment by migueluvieu** [comment]
thank you very much to both! :)
