### ISSUE TITLE
Error in initializing it.

### ISSUE THREAD

**Issue by akshatsd2** [gilf/angular2-indexeddb#24]
client?cd17:80 ./~/angular2-indexeddb/angular2-indexeddb.ts
Module parse failed:node_modules/angular2-indexeddb/angular2-indexeddb.ts Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type.
| import {Injectable} from '@angular/core';
| 
| @Injectable()
| export class AngularIndexedDB {
|     private utils: Utils;
 @ ./~/angular2-indexeddb/index.ts 1:0-37
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi app

**Comment by gilf** [comment]
Hi @akshatsd2,
This isn't a problem in the library but rather a problem of usage.
Did you use npm to install Angular? 
Did you use TypeScript compilerOptions with experimentalDecorators set to true?
If not, you will get the those errors.

**Comment by akshatsd2** [comment]
Did you use npm to install Angular? Yes i did.
Did you use TypeScript compilerOptions with experimentalDecorators set to true? Yes 

I have done both the things and also local storage works in the same project .

**Comment by gilf** [comment]
How do you use it? 
I can see from the error you provided the "Unexpected character '@' (5:0)" and the @Injectable marked. That mean that decorators aren't supported in your build process.

**Comment by akshatsd2** [comment]
I just specified the version of the library    "angular2-indexeddb":"^1.0.10" in my package and then npm install and it is importing fine but when i try to initialize it   
database = new AngularIndexedDB('devDb',1);
It throws this error.
localStorage isn't relevant to the library, I know i am just trying to say that we have webpack and package file so i did the same for it & it worked.

**Comment by gilf** [comment]
The error you are getting is produced by webpack or by the hot reloading module you are using. What it means is that you need an appropriate loader to handle the ts file with the decorator (the @ sign in that decorate the Injectable).
