### ISSUE TITLE
Can you please provide a simple example how to make angular2-indexeddb working with angular 2?

### ISSUE THREAD

**Issue by me-kell** [gilf/angular2-indexeddb#25]
Can you please provide a simple example how to make `angular2-indexeddb` working with Angular (Version 4!)?
I've created an new project with `ng new test-angular2-indexeddb` and installed `angular2-indexeddb` with `npm install angular2-indexeddb`.

The following code produces the error `You need to use the createStore function to create a database before you query it!`:
```
import {Component, OnInit} from '@angular/core';
import {AngularIndexedDB} from 'angular2-indexeddb';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app works3!';
  ngOnInit(): void {
    let db = new AngularIndexedDB('myDb', 1);
    db.createStore(1, (evt) => {
      console.log(evt);  // <- this is never reached!
      let objectStore = evt.currentTarget.result.createObjectStore(
        'people', {keyPath: 'id', autoIncrement: true});
      objectStore.createIndex('name', 'name', {unique: false});
      objectStore.createIndex('email', 'email', {unique: true});
    });
    db.getByKey('people', 1).then((person) => {
      console.log(person);
    }, (error) => {
      console.log(error);
    });
  }
}
```
Other users in [your blog](http://blogs.microsoft.co.il/gilf/2016/02/02/angular2-indexeddb-repository-is-alive/) are reporting this not working and asking for a working example.

**Comment by gilf** [comment]
Hi, 

IndexedDB's API is async and therefore the code you write to use it is also async in it's core. Your problem is that you are calling db.getByKey after db.createStore and db.createStore is async. Your code should change into:

```
db.createStore(1, (evt) => {
      console.log(evt);  // <- this is never reached!
      let objectStore = evt.currentTarget.result.createObjectStore(
        'people', {keyPath: 'id', autoIncrement: true});
      objectStore.createIndex('name', 'name', {unique: false});
      objectStore.createIndex('email', 'email', {unique: true});
    }).then(function() {
       db.getByKey('people', 1).then((person) => {
         console.log(person);
       }, (error) => {
         console.log(error);
       });
    });
```

**Comment by viet0411** [comment]
The following code produces the error "Property 'createStore' does not exist on type 'AngularIndexedDB'". I make angular2-indexeddb working with Angular 4.

`db.createStore(1, (evt) => {
      console.log(evt);  // <- this is never reached!
      let objectStore = evt.currentTarget.result.createObjectStore(
        'people', {keyPath: 'id', autoIncrement: true});
      objectStore.createIndex('name', 'name', {unique: false});
      objectStore.createIndex('email', 'email', {unique: true});
    }).then(function() {
       db.getByKey('people', 1).then((person) => {
         console.log(person);
       }, (error) => {
         console.log(error);
       });
    });`

**Comment by gilf** [comment]
@viet0411,
createStore was replaced by openDatabase function so it doesn't exists. 
Please look at the documentation to understand how to use the service.

**Comment by viet0411** [comment]
@gilf,
Hi, I have fix it. Thanks you.

**Comment by viet0411** [comment]
@gilf ,
Hi, Is there a way to sync data saved on chrome and firefox when using indexedDB? Thanks you.

**Comment by gilf** [comment]
@viet0411,
IndexedDB is a front-end database. Each browser vendor is responsible to create their own implementation which should follow the IndexedDB spec. Due to that there is no way to sync between firefox chrome automatically. You can create some sync but it will be a very cumbersome coding (like some backup/restore functionality)

**Comment by viet0411** [comment]
@gilf ,
Ok, thanks you very much.

**Comment by wbentaala** [comment]
Hello, 
@gilf  i have a problem with IE, that's not working when we add any data. Have you had the same problem? 
Thanks.
