### ISSUE TITLE
How can I get callback result of inserted unique (keypath) id value?

### ISSUE THREAD

**Issue by altaf933** [gilf/angular2-indexeddb#26]
```
return new Promise((resolve, reject) => {
      this.db.add(tableName, data).then((evt) => {
         resolve("success");
      }, (error) => {
        console.log(error);
        reject('fail');
      });
    });
```
After insert a new  item than callback not return updated  id value . How can I get the callback for updated id value?

**Comment by gilf** [comment]
The promise of add is resolved with the key and value so you can use the following to see the key:
`this.db.add(tableName, data).then((addedRecord) => {
         console.log(addedRecord);
      }, (error) => {
        console.log(error);
      });
    });`
