### ISSUE TITLE
add record Promise do not have key set.

### ISSUE THREAD

**Issue by pyarun** [gilf/angular2-indexeddb#27]
```
db.createStore(1, (evt) => {
    let objectStore = evt.currentTarget.result.createObjectStore(
          'org', { keyPath: "id", autoIncrement: true });
  });

 db.add('org', data).then((item)=>{
      console.log(item);
    }, error=>{
      console.error(error);
    })
```
Value of item:
```
{
key:undefined,
value: {
    name: "orgname"
  }
}
```

Value of key is `undefined`

How could i get that.

**Comment by gilf** [comment]
In the code example you set the key to be id and not key (keyPath is set to id and it is auto increment). 
As a result, IndexedDB creates a key index on the id property therefore the key property is undefined if you didn't provide it in the data object.

**Comment by pyarun** [comment]
Agree! in that case we should get `id` as key in `value` map. but that's not happening.
But if i see chrome dev tools, id is generated, and also its been put in key field.
Even if key is not set we should get id in value.

**Comment by gilf** [comment]
Just pushed a commit that should fix this problem.
Thanks for letting me know.
