### ISSUE TITLE
How do i create multiple stores??

### ISSUE THREAD

**Issue by abizit** [gilf/angular2-indexeddb#29]
<p>I am trying to have 2 stores in a single database. But I unable to do so. Documentation only shows how to create a store.</p>

I tried to use the sample code provided:

```
let db = new AngularIndexedDB("myDb", 1);
db.createStore(1, (evt) => {
    let objectStore = evt.currentTarget.result.createObjectStore(
        "people", { keyPath: "id", autoIncrement: true });
    objectStore.createIndex("name", "name", { unique: false });
    objectStore.createIndex("email", "email", { unique: true });
});
db.createStore(2, (evt) => {
    let objectStore2 = evt.currentTarget.result.createObjectStore(
        "pets", { keyPath: "id", autoIncrement: true });
});
```

But it does not work. Am I doing something wrong??

**Comment by fdambrosio** [comment]
you can have multiple stores in the same db ;) 

```
let db = new AngularIndexedDB("myDb", 1);
db.createStore(1, (evt) => {
    let objectStore = evt.currentTarget.result.createObjectStore(
        "people", { keyPath: "id", autoIncrement: true });
    objectStore.createIndex("name", "name", { unique: false });
    objectStore.createIndex("email", "email", { unique: true });

    let objectStore2 = evt.currentTarget.result.createObjectStore(
        "pets", { keyPath: "id", autoIncrement: true });
});
```

**Comment by abizit** [comment]
Thanks, @fdambrosio i was under the impression that a version upgrade was needed to add more stores.

**Comment by gilf** [comment]
@abizit,

As @fdambrosio indicated, you can create more than one store in the db and I'm happy the issue is solved. 
One last thing, the callback in the createStore function will be attached to IndexedDB's onupgradeneeded function. Changing the version should have triggered that function again and add the objectStore. I'll investigate if it works again.

**Comment by thiagoalmedeiros** [comment]
Hi guys, this solution don't work for me. 
My code: 

  LOCAL_STORAGE_NAME = 'birds';
  db = new AngularIndexedDB('BD', 1);

return this.db.openDatabase(1, (evt) => {
      const objectStore = evt.currentTarget.result.createObjectStore(
        this.LOCAL_STORAGE_NAME, { keyPath: 'id', autoIncrement: true });

      objectStore.createIndex('XPTO_id', 'XPTO_id', { unique: false });
      objectStore.createIndex('active', 'active', { unique: false });
      objectStore.createIndex('notificationType', 'notificationType', { unique: false });


      const objectStore2 = evt.currentTarget.result.createObjectStore(
        'pets', { keyPath: 'id', autoIncrement: true });
    });

This code work only to the first create. Can you see where I'm wrong? Thanks.
