### ISSUE TITLE
Error while Build 

### ISSUE THREAD

**Issue by abizit** [gilf/angular2-indexeddb#31]
Im using Angular cli 1.0. When i try to build it gives out these Errors

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Library/WebServer/www/coop/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Library/WebServer/www/coop/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Library/WebServer/www/coop/node_modules/angular2-indexeddb/node_modules/@angular/core/src/di/opaque_token.d.ts
```

**Comment by TallisSouza** [comment]
I've got the same error, but running with `ng build --aot false` works.

I'm using:
angular-cli: 1.0.6
angular: 4.0.0
S.O.: Windows 10

**Comment by HardikDG** [comment]
Any update on this issue, I am still getting same error when I add '--aot false' with run command

**Comment by HardikDG** [comment]
Did you get any solution on this? I am also getting same error

**Comment by gilf** [comment]
Sorry I didn't have time to investigate the issue yet. 
I think it's related to the fact that the service is using previous Angular version (2.4.0). If any of you can change in the service package.json the usage of @angular/core to your current Angular version and check if that solve the problem, it will be helpful.

**Comment by abizit** [comment]
Figured out a way. Had to add paths to the tsconfig.json. Seems to work but i'm not sure if this is the best solution. This is how my tsconfig looks now.
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "paths": {
      "@angular/common": ["../node_modules/@angular/common"],
      "@angular/compiler": ["../node_modules/@angular/compiler"],
      "@angular/core": ["../node_modules/@angular/core"],
      "@angular/forms": ["../node_modules/@angular/forms"],
      "@angular/platform-browser": ["../node_modules/@angular/platform-browser"],
      "@angular/platform-browser-dynamic": ["../node_modules/@angular/platform-browser-dynamic"],
      "@angular/router": ["../node_modules/@angular/router"],
      "@angular/http": ["../node_modules/@angular/http"],
      "angular2-indexeddb": ["../node_modules/angular2-indexeddb"]
    }
  }

}
```

**Comment by HardikDG** [comment]
Yes, @abizit solution worked for me also.

**Comment by Shpektaras** [comment]
After using @abizit fix I've got the new error:

`ERROR in /.../node_modules/angular2-indexeddb/angular2-indexeddb.ts (81,58): Argument of type 'string' is not assignable to parameter of type 'IDBCursorDirection'.
/.../node_modules/angular2-indexeddb/angular2-indexeddb.ts (311,76): Argument of type 'string' is not assignable to parameter of type 'IDBTransactionMode'.
`

I have no idea how to fix it and make angular-indexeddb work :-(

**Comment by kormic** [comment]
@abizit solution doesn't work for me. What worked was the flag --aot false @TallisSouza suggested.

**Comment by danny95djb** [comment]
any progress made on this that isn't a work around?

**Comment by danny95djb** [comment]
is a permanent fix coming for this?

**Comment by benjazz** [comment]
Just remove the folder "node_modules" of the package solve the problem. (this folder is added when you install the package)

In the same way @gilf , it's will be great if you can remove these lines of your package.json : 

"dependencies": {
    "@angular/core": "^2.4.0",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
  },

to "dependencies": {  },

**Comment by gilf** [comment]
@benjazz removed the rxjs and zone dependencies which aren't needed at all. Later on I'll update the angular core dependency.

**Comment by benjazz** [comment]
@gilf Prefect ! thanks
