### ISSUE TITLE
 Can't resolve all parameters for AngularIndexedDB 

### ISSUE THREAD

**Issue by rishparekh** [gilf/angular2-indexeddb#32]
Getting below warning while making build

Warning: Can't resolve all parameters for AngularIndexedDB in angular/node_modules/angular2-indexeddb/angular2-indexeddb.ts: (?, ?). This will become an error in Angular v5.x

Will it be problematic when angular is upgraded in future ?

**Comment by erickyi2006** [comment]
am using angular4 . no issue. 

@angular/cli: 1.0.6
node: 6.10.3
os: win32 x64
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.0.6
@angular/compiler-cli: 4.2.5

**Comment by rishparekh** [comment]
same issue when upgraded angular to 5.0.0-beta.7
build command :- ng build --prod
this warning only comes when trying to make production build

**Comment by gilf** [comment]
I removed the Injectable decorator which isn't necessary anymore. 
That should fix this problem.
