### ISSUE TITLE
Method "remove" removed ...

### ISSUE THREAD

**Issue by evknz** [gilf/angular2-indexeddb#33]
Are you guys aware that the "remove" method doesn't exists in the API ? 

"db.remove ..."

I got lucky trying the db.delete method instead. 

The docs should be updated, if i'm not wrong...

Cheers!

**Comment by danny95djb** [comment]
just submitted a pull request for this after i noticed it at work today, haha.

**Comment by gilf** [comment]
10x for the catch. In the past the method was called remove but I aligned it to IndexedDB naming which is delete.
