### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Affuta** [gilf/angular2-indexeddb#36]
I get the following errors when i try to build my angular app... Any suggestions?

.../node_modules/angular2-indexeddb/angular2-indexeddb.ts (81,58): Argument of type 'string' is not assignable to parameter of type 'IDBCursorDirection'.

.../node_modules/angular2-indexeddb/angular2-indexeddb.ts (311,76): Argument of type 'string' is not assignable to parameter of type 'IDBTransactionMode'.

**Comment by gilf** [comment]
This is happening because of a change in TypeScript IndexedDB API definitions in the last TypeScript version (the previous type was string for both of the arguments and now it's IDBCursorDirection and IDBTransactionMode).

**Comment by Affuta** [comment]
Updated typescript to 2.4.2 
This fixed by problem, thank you for your feedback.
