### ISSUE TITLE
Error during build AOT - Using Angular 4

### ISSUE THREAD

**Issue by gauravkukreja06** [gilf/angular2-indexeddb#38]
Facing this issue in ng build
```
Error in /node_modules/angular2-indexeddb/angular2-indexeddb.ts (81,58): Argument of type 'str
ing' is not assignable to parameter of type 'IDBCursorDirection'.

ERROR in /node_modules/angular2-indexeddb/angular2-indexeddb.ts (311,76): Argument of type 'st
ring' is not assignable to parameter of type 'IDBTransactionMode'. 
```
package.json:
"typescript": "^2.4.2"
"angular/cli": "^1.2.6",
"angular/common": "^4.3.2",
"angular/compiler": "^4.3.2",
"angular/compiler-cli": "^4.3.2",
"angular/core": "^4.3.2",

**Comment by krishna-kumar06** [comment]
I am also facing same issue..

**Comment by krishna-kumar06** [comment]
it seems type script version issue. I am using typescript 2.3.3 and it has openCursor method which is using "IDBCursorDirection" as one of its argument. But in older verisons of Type script string is being used.

**Comment by gilf** [comment]
The same problem as in #36

**Comment by phillipjchambers** [comment]
I'm still seeing this error, even with these:

"typescript": "^2.4.2"
"angular/cli": "^1.2.7",
"angular/common": "^4.3.3",
"angular/compiler": "^4.3.3",
"angular/compiler-cli": "^4.3.3",
"angular/core": "^4.3.3",

Any ideas, pls?

**Comment by WangGuangrong** [comment]
me too

**Comment by gilf** [comment]
Please take the last version which fixes this problem
