### ISSUE TITLE
Import {AngularIndexedDB} from 'angular2-indexeddb'  Not Works

### ISSUE THREAD

**Issue by juanedsa** [gilf/angular2-indexeddb#4]
Hi.

I am try import AngularIndexedDB but not works. I am use 0.0.3 version. 

1. Download from npm:  npm install angular2-indexeddb 
2. Include angular2-indexeddb.js in my application.
3. I am try import AngularIndexedDB but not works. :(

The error 'Cannot find module 'angular2-indexeddb'.'

Thank you

**Comment by gilf** [comment]
Please update to version 1.0.1 and try again.
Also, I recommend to use a bundler (Webpack, Browserify and etc.) instead of adding the file to your app.

**Comment by joseant** [comment]
Hello.
I have tried the version 1.0.1 with 

angular-cli: 1.0.0-beta.19-3
node: 6.5.0
os: win32 x64

I follow this steps:
-  npm install angular2-indexeddb --save
- import {AngularIndexedDB} from './angular2-indexeddb'; in the component
And I get this error:
 ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './angular2-indexeddb' in [...]

Thanks.

**Comment by gilf** [comment]
Please update to version 1.0.3.
I added an index.ts file and declaration file for the service which should solve the problems.
Let me know if that helped.

**Comment by joseant** [comment]
Hello.

I got now two errors:

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './angular2-indexeddb' in 
 @ ./src/app/app.component.ts 11:0-56
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] node_modules\@types\es6-promise\index.d.ts:11:14 
Duplicate identifier 'Promise'.

ERROR in [default] node_modules\@types\es6-promise\index.d.ts:42:18 
Duplicate identifier 'Promise'.

[....]

**Comment by gilf** [comment]
Please use:
`import {AngularIndexedDB} from 'angular2-indexeddb';`
without the `./` to import the service.
The second error isn't related to angular2-indexeddb (it's a problem in es6-promise module)

**Comment by joseant** [comment]
Hello.
With this configuration:
angular-cli: 1.0.0-beta.19-3
node: 6.5.0
os: win32 x64

If I create a new project: ng new test
It works.

Later If I do npm install angular2-indexeddb
and ng serve


ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\@types\es6-promise\index.d.ts:11:14 
Duplicate identifier 'Promise'.

ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\@types\es6-promise\index.d.ts:42:18 
Duplicate identifier 'Promise'.

ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\typescript\lib\lib.es2015.iterable.d.ts:141:10 
Duplicate identifier 'Promise'.

ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\typescript\lib\lib.es2015.promise.d.ts:20:10 
Duplicate identifier 'Promise'.

ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\typescript\lib\lib.es2015.promise.d.ts:187:12 
Duplicate identifier 'Promise'.

ERROR in [default] C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules\typescript\lib\lib.es2015.symbol.wellknown.d.ts:164:10 
Duplicate identifier 'Promise'.

**Comment by vgosain91** [comment]
remove the folder named "es6-promise" in the directory C:\Users\josea\Documents\essentsialist\tests\storage\storage4\node_modules@types.

This will solve the duplicate identifier issue.

**Comment by gilf** [comment]
Hi,

Had time to solve the duplicate issue.
Please grab version 1.0.5 and you will be alright.

**Comment by joseant** [comment]
Thanks. Now is working.

**Comment by alevidcosta** [comment]
import {IndexedDBAngular} from 'indexeddb-angular'; for indexeddb-angular version 0.1.8
