### ISSUE TITLE
[question] Fetch data from existing DB

### ISSUE THREAD

**Issue by majkelch** [gilf/angular2-indexeddb#44]
Hello,

I am struggling with scenario where I already have populated DB and I want to get data from it. 
Let's say scenario looks like this:
* login to app
* click button Create DB which creates and populates DB <- this works fine in latest Chrome and Angular 4.4.4
* logout from app
* login again
* fetch & display exising data

Could you show me how can I fetch existing data?

**Comment by gilf** [comment]
Hi,
You could achieve that using the createStore function. 
On the other hand, your question raise a problem in my function name and therefore I changed the createStore function to openDatabase and the callback is now optional. Please take the new 1.2 version to get the updated code.
