### ISSUE TITLE
"Module build failed" withAngular 5

### ISSUE THREAD

**Issue by GAlexMES** [gilf/angular2-indexeddb#48]
I just updated my project from angular 4 to 5 an noticed, that the plugin is not working anymore.

I generated a new Angular Project and just added the import and  ``let db = new AngularIndexedDB('myDb', 1);`` to the constrcutor of the App Component.

> ERROR in ./node_modules/angular2-indexeddb/index.ts
Module build failed: Error: [...]\node_modules\angular2-indexeddb\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile ([...]\node_modules\@ngtools\webpack src\angular_compiler_plugin.js:625:23)
    at plugin.done.then ([...]\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/_services/database.service.ts 11:0-54
 @ ./src/app/_services/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

I use the following dependencies:

> "@ angular/cli": "1.5.4",
    "@ angular/compiler-cli": "^5.0.0",
    "@ angular/language-service": "^5.0.0",
    "@ types/jasmine": "~2.5.53",
    "@ types/jasminewd2": "~2.0.2",
    "@ types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"

**Comment by marlon360** [comment]
You have to edit your tsconfig.json file:
```json
{
  "compilerOptions": {
   ...
  },
  "include": [
    "../src/**/*",
    "../node_modules/angular2-indexeddb/index.ts"
  ]
}
```
You have to include the index.ts of angular2-indexeddb and all the other sources.

After that the compiler shows a warning.
My pull request #49 solves this problem.

**Comment by gilf** [comment]
@marlon360 I merge the pull request. 10x

**Comment by Cl3r1k** [comment]
In my case with Angular Cli 1.6 next lines should be in tsconfig.app.json instead of tsconfig.json
```
"include": [
    "../src/**/*",
    "../node_modules/angular2-indexeddb/index.ts"
  ]
```

**Comment by digitop** [comment]
In my case Angular Cli 1.7.0 i have to modify the tsconfig.app.json file like @Cl3r1k mentioned before. But i had to add a new entry:
```
"include": [
    "../src/**/*",
    "../node_modules/angular2-indexeddb/index.ts",
    "../node_modules/angular2-indexeddb/angular2-indexeddb.ts",
  ]
```

**Comment by GAlexMES** [comment]
@gilf 

I randomly got this error again today, but just when I run "ng test", "ng serve" works.

ng -v gives me:

```
Angular CLI: 1.7.2
Node: 8.9.1
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.2
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

Any idea what that causes the error?


```
ERROR in ./node_modules/angular2-indexeddb/index.ts
Module build failed: Error: C:\Users\.....\node_modules\angular2-indexeddb\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\....\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\....\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/core/_services/_database/database.service.ts 12:27-56
 @ ./src/app/core/_services/_serverconnection/authentication.service.ts
 @ ./src/app/core/_services/_serverconnection/request-week.service.ts
 @ ./src/app/core/_services/_serverconnection/request-week.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
```
