### ISSUE TITLE
Using Injectable with mandatory primitive type constructor parameters

### ISSUE THREAD

**Issue by johnhamm** [gilf/angular2-indexeddb#50]
Using @Injectable denotes you want to use DI, yet your constructor has two primitive type mandatory parameters which are not wrapped in Inject so can't be injected.  This isn't compatible with Angular 5 and gives an error:

> Warning: Can't resolve all parameters for AngularIndexedDB in node_modules/angular2-indexeddb/angular2-indexeddb.ts: (?, ?). This will become an error in Angular v5.x

Why not simply remove the Injectable decorator, or make the class an injectable service?

**Comment by gilf** [comment]
@johnhamm 
You are right. 
The Injectable decorator was used in the past but isn't needed anymore. 
I removed it and updated the repository.
