### ISSUE TITLE
Error While Loading the Application

### ISSUE THREAD

**Issue by mohamed-magdy** [gilf/angular2-indexeddb#54]
i am new in using this service and i go through the examples and try to create my example but every time i load the application this errors showed up :
 in [at-loader] ./node_modules/angular2-indexeddb/angular2-indexeddb.ts:265:9 
    TS2322: Type 'null' is not assignable to type 'IDBDatabase'.
ERROR in [at-loader] ./node_modules/angular2-indexeddb/angular2-indexeddb.ts:285:9 
    TS2322: Type '((e: Event) => any) | undefined' is not assignable to type '(this: IDBTransaction, ev: Event) => any'.
  Type 'undefined' is not assignable to type '(this: IDBTransaction, ev: Event) => any'.

Could you help me please finding the reason of these errors.

**Comment by gilf** [comment]
Did you run the openDatabase function? it is mandatory before any operation you are doing.
Also, take into care that the openDatabase function is async.
