### ISSUE TITLE
README.md may not be up to date

### ISSUE THREAD

**Issue by jubil** [gilf/angular2-indexeddb#55]
In the file '**README.md** ' I can read:

```
db.openCursor('people', (evt) => {
    var cursor = evt.target.result;
    if(cursor) {
        console.log(cursor.value);
        cursor.continue();
    } else {
        console.log('Entries all displayed.');
    }
}, IDBKeyRange.bound("A", "F"));
```
But, I have an error on the line 
`var cursor = evt.target.result;`
* The '**result**' property does not exist on the '**EventTarget**' type.

**Comment by gilf** [comment]
@jubil,
Thanks for your point.
You can cast evt.target to type any to solve the problem.
I'll update the readme file to express that.
