### ISSUE TITLE
Not working in IE edge

### ISSUE THREAD

**Issue by curious29** [gilf/angular2-indexeddb#56]
I tried indexed db in IE Edge but it is giving Data Error

**Comment by gilf** [comment]
Can you be more specific?
I've checked the library and it is working in IE Edge.

**Comment by andrey-yumasoft** [comment]
At least update and add methods don't work in Edge when called without `key` parameter. 
If I remove `key` at objectStore.put(value, key); at update method code it starts working in Edge.

**Comment by StudioKodeMike** [comment]
I am also getting this error when trying to use add() 

Is there a fix for this?

**Comment by Bobgentry** [comment]
I'm also having the same problem.
I really need a workaround for this
