### ISSUE TITLE
 Cannot find name 'IDBCursorDirection'

### ISSUE THREAD

**Issue by JuanCalderon** [gilf/angular2-indexeddb#57]
I get this two errors:

default] /Users/calderon/gdrive/smilodon/projects/angular2-cli/lungo5/node_modules/angular2-indexeddb/angular2-indexeddb.ts:76:59 
    Cannot find name 'IDBCursorDirection'.
[default] /Users/calderon/gdrive/smilodon/projects/angular2-cli/lungo5/node_modules/angular2-indexeddb/angular2-indexeddb.ts:281:61 
    Cannot find name 'IDBTransactionMode'.
[default] Checking finished with 2 errors

My versions:
@angular/cli: 1.4.4
node: 6.10.3
os: darwin x64
angular/common: 2.0.0
angular/compiler: 2.0.0
angular/core: 2.0.0
angular/forms: 2.0.0
angular/http: 2.0.0
angular/platform-browser: 2.0.0
angular/platform-browser-dynamic: 2.0.0
angular/router: 3.0.0
ngtools/webpack: 1.1.8
typescript: 2.4.2

Thanks

**Comment by gilf** [comment]
@JuanCalderon 
The problem you are getting is due to not updated TypeScript's lib.es6.d.ts file. Please use the following in your package.json: "typescript": "^2.4.2", run npm install again and check if that helps to solve the problem.
