### ISSUE TITLE
Problems with the upgrade process

### ISSUE THREAD

**Issue by GAlexMES** [gilf/angular2-indexeddb#59]
I am not sure if I just didn't understand it corecctly or if there is an error in the implementation.

```
this.database = new AngularIndexedDB('db', 3);

this.database.openDatabase(3, 
    (evt) => {
        console.log("version 3");
    }(error) => {
      console.log(error);
    }
);

this.database.openDatabase(2, 
    (evt) => {
        console.log("version 2");
    }(error) => {
      console.log(error);
    }
)
```

I expected the following behavior:

- When I already have a Version 3 Database in my browser nothing happens.
- When I already have a Version 2 Database "version 3" would be printed.
- When I have no database or a Version 1 Database "version 2" and "version 3" will be printed"

But the behavior is, that I get an error as soon as I try to open a database with a different version then I initialized it. So in this example openDatabase(2,....) would throw the error.

The error is:

> ERROR Error: Uncaught (in promise): IndexedDB error: undefined
>     at resolvePromise (zone.js:809)
>     at eval (zone.js:728)
>     at IDBOpenDBRequest.request.onerror [as __zone_symbol__ON_PROPERTYerror] (angular2-indexeddb.ts:23)
>     at IDBOpenDBRequest.wrapFn (zone.js:1166)
>     at ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:4740)
>     at ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.runTask (zone.js:188)
>     at ZoneTask.invokeTask [as invoke] (zone.js:496)
>     at invokeTask (zone.js:1517)

If I missunderstood something please close this Issue and let me know, how to do it correct.

**Comment by gilf** [comment]
@GAlexMES,

You are trying to run two async operations in parallel and ending up with that error.
In order to correct your code you will have to run the second open in the then function of the first open call.

```
this.database.openDatabase(3, 
    (evt) => {
        console.log("version 3");
        this.database.openDatabase(2, ...)
    }(error) => {
      console.log(error);
    }
) 
```

**Comment by GAlexMES** [comment]
@gilf 

Okay, I tried it. It works, when I already have a version 3 database in my browser.
But when I have a version 0, 1 or 2 it failes, when I try to open it in an older version. So in your example "version 3" would be printed to the console and then I got an error.

Thanks for your help.

**Comment by gilf** [comment]
@GAlexMES,

Thanks for letting me know. 
I'm closing this issue and if I'll have any fix, I'll comment here.
