### ISSUE TITLE
Issues with get functions

### ISSUE THREAD

**Issue by benj13260** [gilf/angular2-indexeddb#6]
Hi,

First thank you for sharing this library :+1: 

I have created a source component to experiment: [off-site.component.txt](https://github.com/gilf/angular2-indexeddb/files/621484/off-site.component.txt)

These functions are perfectly working:

- Create a new IndexedDB
- Add entry
- Remove entry
- Display all entries through the function "Cursor"

Nevertheless the other functions doesn't seem to work as they all return "undefined"

- getAll
- getByIndex
- getByKey

I have copied exactly the samples you described (nevertheless I might be doing something wrong)

Thanks in advance for your answer.

Regards,
Ben

**Comment by gilf** [comment]
Hi @benj13260,

Thanks for letting me know and for using the library.
I've just uploaded a new version with fixes to that. 

Let me know if it's working for you and I'll close this issue.

Best regards,
Gil

**Comment by benj13260** [comment]
Hi,

All good!

Thanks for the reactivity :)

Regards,
Ben
