### ISSUE TITLE
5659:15-36 Critical dependency: the request of a dependency is an expression 

### ISSUE THREAD

**Issue by veluvj** [gilf/angular2-indexeddb#61]
i just want to use read-more-directive-angular2 .but it shows

`WARNING in /home/veluvijay/web__app/client-frontend/node_modules/read-more-directive-angular2/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression`

**Comment by gilf** [comment]
Not related to angular2-indexeddb
