### ISSUE TITLE
Cannot build application with angular2-indexeddb - angular2-indexeddb.ts' is not under 'rootDir'

### ISSUE THREAD

**Issue by Brunogr** [gilf/angular2-indexeddb#62]
When running "ngc -p src/tsconfig.lib.json" i get this error:

`error TS6059: File 'C:/git/sdk-components-front/node_modules/angular2-indexeddb/angular2-indexeddb.ts' is not under 'rootDir' 'C:/git/sdk-components-front/src'. 'rootDir' is expected to contain all source files.`

Here are my tsconfig.lib.json:

> {
>   "extends": "../tsconfig.json",  
>   "compilerOptions": {  
>     "outDir": "../dist",  
>     "baseUrl": "./",  
>     "module": "es2015",  
>     "types": [],  
>     "paths": {  
>       "@angular/*": ["../node_modules/@angular/*"],  
>       "angular2-indexeddb": ["../node_modules/angular2-indexeddb"]  
>     }  
>   },  
>   "exclude": [  
>     "test.ts",  
>     "**/*.spec.ts",  
>     "../node_modules/*",  
>     "typings.d.ts"  
>   ]  
> }

tsconfig.json:

> {
>   "compileOnSave": false,
>   "compilerOptions": {
>     "rootDir": "src",
>     "sourceMap": true,
>     "declaration": false,
>     "moduleResolution": "node",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "target": "es5",
>     "typeRoots": [
>       "node_modules/@types"
>     ],
>     "lib": [
>       "es2015",
>       "dom"
>     ]
>   }
> }
> 

What can possible be wrong?

**Comment by gilf** [comment]
@Brunogr,
This is happening because you are using rootDir configuration in your tsconfig.json. 
rootDir is configuring were all the source files are coming from. Here is TypeScript definition for rootDir in their documentation: 

> Specifies the root directory of input files. Only use to control the output directory structure with --outDir. 

You should use outDir as indicated in TypeScript documentation.
