### ISSUE TITLE
Property 'value' does not exist on type 'IDBDatabase'. angular 7.0

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [gilf/angular2-indexeddb#68]
I recently upgraded to version 7.0 from angular and I'm with the following error.

ERROR in node_modules/angular2-indexeddb/angular2-indexeddb.ts(89,40): error TS2339: Property 'value' does not exist on type 'IDBDatabase'.

**Comment by spikalev** [comment]
the same error, the library is unusable with angular 7.

**Comment by zhrichard** [comment]
The same issue here, is the fix on the road?

**Comment by spikalev** [comment]
guys, check my changes from PR pull #69 
it solves the problem for me.

**Comment by leer6** [comment]
Verified, this pull request resolves the issue. Good job !

**Comment by zhrichard** [comment]
> The same issue here, is the fix on the road?

Verified, compilation error is gone. Thanks for quick fix!

**Comment by gilf** [comment]
Merged #69

**Comment by imbernal** [comment]
Hi guys, I made npm install and still have the same issue.

**Comment by ziajka** [comment]
I think update hasn't been released yet: https://www.npmjs.com/package/angular2-indexeddb

**Comment by imbernal** [comment]
When are you going to make a release? Because I need to release my app, and I am having this issue. Thanks

**Comment by gilf** [comment]
@imbernal 
I've published a minor version which should have the merged pull request with the fix
