### ISSUE TITLE
[Feature Request] order by index and iterate over object ascending or descending order 

### ISSUE THREAD

**Issue by zeet2020** [gilf/angular2-indexeddb#8]
getAll method fetch items but it does not really provide a way to index and order by in ascending or descending order while iterating over the objects 

can we have implementation to index and order something like this 

`getAll(storeName: string,indexBy:string,Order:string = "asc") {
        let self = this;
        let promise = new Promise<any>((resolve, reject)=> {
            self.dbWrapper.validateBeforeTransaction(storeName, reject);

            let transaction = self.dbWrapper.createTransaction({ storeName: storeName,
                    dbMode: self.utils.dbMode.readOnly,
                    error: (e: Event) => {
                        reject(e);
                    },
                    complete: (e: Event) => {
                    }
                }),
                objectStore = transaction.objectStore(storeName),
                result = [],
                if(indexBy){
                     let Ord = (Order === 'desc')? 'prev' : 'next';
                    request = objectStore.index(indexBy).openCursor(null,Ord);
                }else {
                     request = objectStore.openCursor();
               }
                

            request.onerror = function (e) {
                reject(e);
            };`

**Comment by gilf** [comment]
Just pushed those options. 
Thanks for the suggestion and sorry for the late update.
