### ISSUE TITLE
You need to use the createStore function to create a database before you query it!

### ISSUE THREAD

**Issue by LamaBimal** [gilf/angular2-indexeddb#9]
I have created the database using constructor. and used the same reference to add the element but i got this error. How could I resolve it.
/**
 * Created by bimal on 12/6/16.
 */
import {Injectable} from '@angular/core';
import {product} from './product'
import {AngularIndexedDB} from "angular2-indexeddb";

@Injectable()
export class productService{
     private products:product[];
     db:any;
     objectStore:any;
    constructor(){
         this.db = new AngularIndexedDB("@productDB",1);
        this.db.createStore(1,(evt)=>{
            this.objectStore = evt.currentTarget.result.createObjectStore('products',{keyPath:"_generatedKey"});
                this.objectStore.createIndex("productId","productId",{unique:true});
                this.objectStore.createIndex("productName","productName",{unique:false});
        });

    }
     setProducts(_product:any[]):void{
         console.log(_product.length);
         this.products = new Array(_product.length);
        for(let i=0;i<_product.length;i++){
            this.products.push(new product(_product[i].id,_product[i].name,_product[i].price,_product[i].price,_product[i].tags,_product[i].description));
        }
       /* var productObjectStore = this.db.transaction("products","readwrite").objectStore("products");*/

         for(var j in this.products)
         {

             console.log(JSON.stringify(this.products[j]));
            // productObjectStore.add(this.products[j]);

             this.db.add('products',this.products[j]);
         }

     }
}

**Comment by gilf** [comment]
Hi @LamaBimal,

After you run the constructor in your app. Please go to browser developer tools and open the Application tab. Then, go to the IndexedDB db representation and inspect it to see if the objectStore was created. 
This error you mention is thrown only if the objectStore that you try to query wasn't created.
